title: Teorija programskih jezikov
author: Matija Pretnar
repository:
  url: 'https://github.com/matijapretnar/teorija-programskih-jezikov'
  book_path: zapiski
  branch: zapiski
launch_buttons:
  binderhub_url: 'https://mybinder.org'
sphinx:
  config:
    mathjax_config:
      tex:
        macros:
          "intsym": ["\\underline{#1}", 1]
          "kwd": ["\\mathbf{#1}", 1]
          "kwdpre": ["\\kwd{#1}\\;", 1]
          "kwdmid": ["\\;\\kwd{#1}\\;", 1]
          "kwdpost": ["\\;\\kwd{#1}", 1]
          "true": "\\kwd{true}"
          "false": "\\kwd{false}"
          "ifthenelse": ["\\kwdpre{if} #1 \\kwdmid{then} #2 \\kwdmid{else} #3", 3]
          "whiledo": ["\\kwdpre{while} #1 \\kwdmid{do} #2", 2]
          "skip": "\\kwd{skip}"
          "fst": "\\kwdpre{fst}"
          "snd": "\\kwdpre{snd}"
          "inl": "\\kwdpre{inl}"
          "inr": "\\kwdpre{inr}"
          "match": "\\kwdpre{match}"
          "with": "\\kwdmid{with}"
          "matchsum": ["\\match #1 \\with \\inl #2 \\mapsto #3 \\; \\inr #4 \\mapsto #5", 5]
          "matchlist": ["\\match #1 \\with [] \\mapsto #2 \\; #3 :: #4 \\mapsto #5", 5]
          "ttt": "t\\!t"
          "fff": "f\\!\\!f"
          "infer": ["\\displaystyle{\\frac{#1}{#2}}", 2]
          "boolty": "\\kwd{bool}"
          "intty": "\\kwd{int}"
          "eqs": "\\mathcal{E}"
          "ctxt": "\\mathcal{C}"
          "itp": ["[\\![ #1 ]\\!]", 1]
          "return": "\\kwdpre{return}"
          "letin": ["\\kwdpre{let} #1 \\kwdmid{in}", 1]
          "bind": "\\mathop{>\\!\\!\\!>\\!\\!\\!=}"
          "just": "\\kwdpre{Just}"
          "nothing": "\\kwdpre{Nothing}"

